- name: Include variables of all.yml file
  include_vars:
    name: included_vars
    file: "{{ inventory_dir }}/group_vars/all.yml"

- name: Merge inventory all variables
  set_fact:
    merged_vars: '{{ merged_vars | combine(included_vars, recursive=True) }}'